---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-service-config
  namespace: ssle-project
data:
  REGISTRY_SERVICE_PORT: "5050"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-service-config
  namespace: ssle-project
data:
  STORAGE_SERVICE_PORT: "5002"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestion-service-config
  namespace: ssle-project
data:
  SERVICE_PORT: "5001"
  STORAGE_SERVICE_URL: "http://storage-service:5002"
  REGISTRY_SERVICE_URL: "http://registry-service:5050"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: ssle-project
data:
  ANALYTICS_SERVICE_PORT: "5003"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temperature-service-config
  namespace: ssle-project
data:
  INGESTION_SERVICE_URL: "http://ingestion-service:5001"
